kind: pipeline
name: default

steps:
  - name: install
    image: composer
    commands:
      - composer install --dev

  - name: test
    image: php:7-apache
    commands:
      - docker-php-ext-install pdo_mysql
      - echo "<?php return ['class' => 'yii\db\Connection','dsn' => 'mysql:host=mysql_db;dbname=test_db','username' => 'test_user','password' => 'test_pass','charset' => 'utf8']; ?>" > config/db.php
      - echo "<?php return ['class' => 'yii\db\Connection','dsn' => 'mysql:host=mysql_db;dbname=test_db','username' => 'test_user','password' => 'test_pass','charset' => 'utf8']; ?>" > config/test_db.php
      - php yii migrate --interactive=0
      - php yii serve
      - vendor/bin/codecept run

services:
  - name: mysql_db
    image: mysql:5
    ports:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'test_pass'

  - name: selenium
    image: selenium/standalone-chrome