kind: pipeline
name: default

steps:
  - name: install-composer
    image: composer
    volumes:
    - name: webdata
      path: /drone/src
    commands:
      - composer install --dev

  - name: run-test
    image: php:7-fpm
    allow_failure: true
    volumes:
    - name: webdata
      path: /drone/src
#    ports:
#      - 80
#      - 8080:8080
    commands:
#      - sleep 90 
      - apt-get update -y && apt-get install -y libpng-dev libmagickwand-dev && pecl install imagick && docker-php-ext-enable imagick
      - docker-php-ext-install pdo pdo_mysql gd
#      - apt-get update && apt-get install -y wget #libmagickwand-dev --no-install-recommends && pecl install imagick && docker-php-ext-enable imagick
#      - docker-php-ext-install pdo_mysql
#      - php yii serve 2>&1 &
      - echo "<?php return ['class' => 'yii\db\Connection','dsn' => 'mysql:host=mysql_db;dbname=test_db','username' => 'test_user','password' => 'test_pass','charset' => 'utf8']; ?>" > config/db.php
      - echo "<?php return ['class' => 'yii\db\Connection','dsn' => 'mysql:host=mysql_db;dbname=test_db','username' => 'test_user','password' => 'test_pass','charset' => 'utf8']; ?>" > config/test_db.php
      - php yii migrate --interactive=0
#      - wget -v http://testserver/index.php && ls -l
#      - wget -v http://testserver/web/index.php && ls -l
#      - wget -v http://testserver:8080/index.php && ls -l
#      - ls -lisah
#      - cat index.php
      - vendor/bin/codecept run --steps --xml --html
      - php yii test/test
      
  - name: ftpupload
    image: cschlosser/drone-ftps
    hostname: alfa3054.alfahosting-server.de:21
    secrets: [ ftp_username, ftp_password ]
    dest_dir: /drone/src/tests/_output/
    when:
      branch:
      - master

    
services:
  - name: mysql_db
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'test_pass'

  - name: selenium
    image: selenium/standalone-chrome
#    ports:

  
  - name: testserver
    image: php:7-fpm
    ports:
      - 80
      - 8080
    volumes:
    - name: webdata
      path: /drone/src
    commands:
      - apt-get update -y && apt-get install -y libpng-dev libmagickwand-dev && pecl install imagick && docker-php-ext-enable imagick
      - docker-php-ext-install pdo pdo_mysql gd
      - php -S testserver:8080 -t ./web
