kind: pipeline
name: default

steps:
  - name: install-composer
    image: composer
    volumes:
    - name: webdata
      path: /drone/src
    commands:
      - composer install --dev

  - name: run-test
    #image: php:7-fpm
    image: toschqlb/php-test-server
    failure: ignore
    volumes:
    - name: webdata
      path: /drone/src
    commands:
#      - apt-get update -y && apt-get install -y libpng-dev libmagickwand-dev && pecl install imagick && docker-php-ext-enable imagick
#      - docker-php-ext-install pdo pdo_mysql gd
      - echo "<?php return ['class' => 'yii\db\Connection','dsn' => 'mysql:host=mysql_db;dbname=test_db','username' => 'test_user','password' => 'test_pass','charset' => 'utf8']; ?>" > config/db.php
      - echo "<?php return ['class' => 'yii\db\Connection','dsn' => 'mysql:host=mysql_db;dbname=test_db','username' => 'test_user','password' => 'test_pass','charset' => 'utf8']; ?>" > config/test_db.php
      - php yii migrate --interactive=0
      - vendor/bin/codecept run --xml --html --json --phpunit-xml --report
      - php yii test/test

  - name: test-test
    image: php:7-fpm
    volumes:
      - name: webdata
        path: /drone/src
    failure: ignore
    commands:
      - php yii test/test

  - name: ftpupload
    image: cschlosser/drone-ftps
    hostname: 'alfa3054.alfahosting-server.de:21'
    password: '1234567890?'
    source_dir: /drone/src/tests/_output/
    environment:
      FTP_USERNAME: 'web739f4'
      FTP_PASSWORD: '1234567890?'
      PLUGIN_HOSTNAME: 'alfa3054.alfahosting-server.de:21'
      PLUGIN_SRC_DIR: '/tests/_output/'

    
services:
  - name: mysql_db
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'test_pass'

  - name: selenium
    image: selenium/standalone-chrome

  - name: testserver
    #image: php:7-fpm
    image: toschqlb/php-test-server
    ports:
      - 80
      - 8080
    volumes:
    - name: webdata
      path: /drone/src
    commands:
      #- apt-get update -y && apt-get install -y libpng-dev libmagickwand-dev && pecl install imagick && docker-php-ext-enable imagick
      #- docker-php-ext-install pdo pdo_mysql gd
      - php -S testserver:8080 -t ./web
