kind: pipeline
name: default

steps:
  - name: install-composer
    image: composer
    volumes:
    - name: webdata
      path: /drone/src
    commands:
      - composer install --dev

  - name: configure-app
    image: toschqlb/php-test-server
    volumes:
      - name: webdata
        path: /drone/src
    commands:
      - echo "<?php return ['class' => 'yii\db\Connection','dsn' => 'mysql:host=mysql_db;dbname=test_db','username' => 'test_user','password' => 'test_pass','charset' => 'utf8']; ?>" > config/db.php
      - echo "<?php return ['class' => 'yii\db\Connection','dsn' => 'mysql:host=mysql_db;dbname=test_db','username' => 'test_user','password' => 'test_pass','charset' => 'utf8']; ?>" > config/test_db.php

  - name: yii-migrate
    image: toschqlb/php-test-server
    failure: ignore
    volumes:
      - name: webdata
        path: /drone/src
    commands:
      - php yii migrate --interactive=0

#  - name: run-test
#    image: toschqlb/php-test-server
#    volumes:
#    - name: webdata
#      path: /drone/src
#    commands:
#      - vendor/bin/codecept run --xml --html --json

  - name: ubuntu-test
    image: ubuntu:bionic
    commands:
      - apt-get -y update && apt-get install -y sshpass
      - echo "cd /var/www/html && vendor/bin/codecept run --xml --html --json" | sshpass -p sshp ssh -T sshuser@testserver

  - name: upload-result
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: ftp_username
      FTP_PASSWORD:
        from_secret: ftp_passwort
      PLUGIN_HOSTNAME:
        from_secret: ftp_host
      PLUGIN_SRC_DIR: '/tests/_output/'
    when:
      status:
        - success
        - failure

  - name: process-results
    image: php:7-fpm
    volumes:
      - name: webdata
        path: /drone/src
    failure: ignore
    commands:
      - php yii test/test
    when:
      status:
        - success
        - failure

services:
  - name: mysql_db
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'test_pass'

  - name: selenium
    image: selenium/standalone-chrome

  - name: testserver
    image: toschqlb/php-test-server
    ports:
      - 80
      - 8080
    volumes:
    - name: webdata
      path: /drone/src
    commands:
      - apt-get install -y openssh-server
      - service ssh start
      - useradd -p $(openssl passwd -1 sshp) sshuser
      - php -S testserver:8080 -t ./web
